### ISSUE TITLE
why create action for each episode intead of only one

### ISSUE THREAD

**Issue by shopconan** [abe-101/YouTube-Podcast#1]
sir  as you know github got free tier of github action monthly limit 3000?
Upload Full YouTube Channel to Podcast

before
```

      - name: Build YouTube Channel Podcast
        uses: abe-101/Build-YouTube-Podcast@main
        env:
          URL: ${{ github.event.inputs.environment }}
```

grab video id using youtube-dl and save as episode.json?
